### ISSUE TITLE
docker-compose now seems to be docker compose as of v2.4.1

### ISSUE THREAD

**Issue by Lusiphur** [Akkadius/akk-stack#10]
I had to sed change that globally in the makefile. Setting an alias for docker-compose didn't seem to work.

OS - Ubuntu 22.04
Docker Compose version - 2.4.1

**Comment by xackery** [comment]
@Lusiphur  I ran into the same issue, my resolution was to download https://github.com/docker/compose/releases docker-compose binary matching version `docker compose version` states, (mine was 2.5.0) and copying it to my /bin/ dir with chmod +x , that'd make all the commands work fine.

**Comment by Akkadius** [comment]
I'll update the readme with instructions on what I've used for this as Docker's documentation is a bit lack luster

**Comment by HighOnMikey** [comment]
fwiw I just created `/usr/bin/docker-compose` to redirect to `docker compose`.

```bash
cat <<EOF | sudo tee /usr/bin/docker-compose
#!/bin/sh
docker compose "\$@"
EOF
sudo chmod +x /usr/bin/docker-compose
```

`akk-stack` worked without issues using latest versions, Docker 20.10.17 and Docker Compose 2.6.0.

**Comment by Akkadius** [comment]
Instructions updated yesterday https://github.com/Akkadius/akk-stack#installing-docker-compose
