### ISSUE TITLE
Cant get server to start.

### ISSUE THREAD

**Issue by bchilton9** [Akkadius/akk-stack#11]
My server was running fine for a long time. I haven't played on it for like a year and decided to connect again and i cant get the server to start now. The server_status.sh just shows everything DOWN. I cant access the admin page on port 3000 i just get connection refused. and when i run the server_start.sh i just get spamed with No such file or directory.

sh: ./zone: No such file or directory
sh: ./queryserv: No such file or directory
sh: ./ucs: No such file or directory
sh: ./world: No such file or directory

I haven't changed any setting or files related to the eq server. its just been siting there idle for about a year. I have no idea what to do or check next to get it working again.

Thank you

**Comment by bchilton9** [comment]
I did run the update in the console AFTER trying to connect thinking there might be an update and it didn't make any difference on getting the server back up.

**Comment by bchilton9** [comment]
i have deleted everything and reinstalled. still the same problem

**Comment by Akkadius** [comment]
This setup does not use the shell utility scripts that you have shown as errors
