### ISSUE TITLE
ip address resolution for loginserver is a bit wonky

### ISSUE THREAD

**Issue by xackery** [Akkadius/akk-stack#12]
So, that's interesting.
Messing with akk-stack and getting login working on a new server I'm spinning up. 
world->tcp->ip can stay at 0.0.0.0
world->localaddress needs to be WAN IP or else when you try to log in via projecteq, it'll attempt to connect via that (e.g. I had 127.0.0.1 , and my packet when server listing was replied on 5999 was this value)
world->address needs to be WAN IP or else when you try to log in via your personal login server, it'll attempt to connect via that (e.g. I had 0.0.0.0, and my packet when server listing was replied on 5999 was this value)
when I spun up akk-stack, originally I had put my WAN ip address, but then docker-compose would spin up and inform me it can't bind to provided address (needs to be 0.0.0.0)

**Comment by Akkadius** [comment]
Networking considerations certainly have to be made when using containers, especially in LAN. I'll see about making some documentation sections making this clearer for folks

**Comment by Akkadius** [comment]
https://github.com/Akkadius/akk-stack#networking-on-lan
