### ISSUE TITLE
considering adding a note about sudo chmod 666 /var/run/docker.sock

### ISSUE THREAD

**Issue by xackery** [Akkadius/akk-stack#13]
akk-stack can be ran without root (the instructions seem to imply it needs it, since the examples are # prompts)
The only step needed to be noted is that during the README, add a comment about needing to run `sudo chmod 666 /var/run/docker.sock` to give current user access to the docker environment (maybe in the requirements section)?

This is really optional and can be closed as a 'true' issue, but just wanted to note it was an undocumented step I did to get things spun up.

**Comment by Akkadius** [comment]
I don't run any of my deployments with root in docker nor in container. Giving a non-root user permissions to run docker in a linux environment are here: https://docs.docker.com/engine/install/linux-postinstall/
