### ISSUE TITLE
dropbox backup needs some review

### ISSUE THREAD

**Issue by xackery** [Akkadius/akk-stack#14]
- [ ] README seems to not use the `make` commands noted inside the Makefile, e.g. `make backup-dropbox-init` can be ran instead of the README's note of `root@host:/opt/eqemu-servers/peq-production# docker-compose exec backup-cron bash`
- [ ] the steps inside latest `make backup-dropbox-init` has changed since the README was written. The steps for setting up the app are roughly the same (I was able to generate a key etc), but the prompts for app key/secret aren't prompted anymore, just for token
- [ ] When I run `$ make backup-dropbox-list` I get the following results, and. I'm not fully sure next steps
```docker-compose up -d backup-cron
[+] Running 1/0
 ⠿ Container eqemu-backup-cron-1  Running                                                                                                                                    0.0s
docker-compose exec backup-cron dropbox_uploader.sh list
 > Listing "/"... FAILED
Some error occured. Please check the log.
make: *** [Makefile:276: backup-dropbox-list] Error 1
```
- [ ] running `make backup-dropbox-database` gives a similar failure:
```
$ make backup-dropbox-database
docker-compose exec backup-cron ./backup/backup-database.sh
# Dumping database and compressing
peq-05-21-2022.sql
# Uploading database snapshot
 > Uploading "/tmp/peq-05-21-2022.tar.gz" to "/req/database-snapshots/peq-05-21-2022.tar.gz"... FAILED
An error occurred requesting /upload
Some error occured. Please check the log.
# Truncating req/database-snapshots days back 10
# Cleaning up...
```

**Comment by xackery** [comment]
The Please check the log appears to be based on the dropbox_upload.sh that akk-stack uses third party, I peeked at that shell script, and I can't easily find teh log file. I will dive deeper in that if you'd like.. but yeah, the whole flow seems to not work with latest dropbox API, or I severely messed it up on some step... can't fully tell yet, first time using akk-stack. :)

**Comment by Akkadius** [comment]
@xackery Just seeing this.

Dropbox did change their API so it probably messed up the instructions a bit. I had to move several dozen deployments over to it back in January

I'll double check the documentation

**Comment by Akkadius** [comment]
I ran through these steps manually myself and updated the documentation. Please let me know if you run into snags.

https://github.com/Akkadius/akk-stack/blob/master/README.md#automated-backups
