### ISSUE TITLE
Permissions problem with dropbox uploader script

### ISSUE THREAD

**Issue by catapultam-habeo** [Akkadius/akk-stack#15]
at last stage of running dropbox_uploader.sh, this is thrown

`Looks ok? [y/N]: y
/bin/dropbox_uploader.sh: line 1623: /home/backup-cron/.dropbox_uploader: Permission denied
/bin/dropbox_uploader.sh: line 1624: /home/backup-cron/.dropbox_uploader: Permission denied
/bin/dropbox_uploader.sh: line 1625: /home/backup-cron/.dropbox_uploader: Permission denied
/bin/dropbox_uploader.sh: line 1626: /home/backup-cron/.dropbox_uploader: Permission denied
   The configuration has been saved.
root@pyrelight-prod:/opt/eqemu#`

The fix was to set permission for /opt/eqemu to user 1000 temporarily.

**Comment by Akkadius** [comment]
This will happen if the akk stack folder was cloned as root instead of a non root user (1000)

**Comment by catapultam-habeo** [comment]
> This will happen if the akk stack folder was cloned as root instead of a non root user (1000)

How do you interact with docker without root?

**Comment by Akkadius** [comment]
It’s in the readme https://github.com/Akkadius/akk-stack#install-docker

**Comment by catapultam-habeo** [comment]
> It’s in the readme https://github.com/Akkadius/akk-stack#install-docker

I'm gonna go away now, lol

**Comment by Akkadius** [comment]
> > It’s in the readme https://github.com/Akkadius/akk-stack#install-docker
> 
> I'm gonna go away now, lol

LOL. No worries
