### ISSUE TITLE
PEQ Editor and PhpMyAdmin unable to connect to MySQL

### ISSUE THREAD

**Issue by docfunfrock** [Akkadius/akk-stack#17]
I spun up a server recently, and most everything is working great.  However, something seems to have gone wonky with the credentials used by the PEQ Editor and PhPMyAdmin to connect to the database.  The error I'm seeing when I visit `<server_ip>:8081` in a browser is:

```
Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'eqemu'@'172.18.0.6' (using password: YES) in /var/www/html/classes/mysqli.php on line 6
Could not connect: Access denied for user 'eqemu'@'172.18.0.6' (using password: YES)
```

I see more or less the same thing when I try to open PhpMyAdmin after providing the credentials:

<img width="656" alt="Screenshot 2022-08-31 103250" src="https://user-images.githubusercontent.com/112577013/187742631-a7f733cf-d0aa-47de-988c-213a917753c2.png">

I _also_ have a problem when I try to run `make mc` on the host, although that looks like a slightly different configuration issue:
```
docker-compose exec mariadb bash -c "mysql -uroot -p<password> -h localhost peq"
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
make: *** [Makefile:169: mc] Error 1
```

But the database is up and running.  It works fine in the game, and if I run `make bash` followed by `mc` then I'm able to get a database shell.

Is there any automated way I can regenerate and maybe fix all these credentials?

Thanks for all your work on this project, it's amazing.

**Comment by Akkadius** [comment]
@docfunfrock looks like something got messed up along the way in the install, potentially you scrambled passwords again after install or something to that extent. There's no reason that this would happen from just `make install`

I would create a fresh deployment install

**Comment by docfunfrock** [comment]
All right, thanks, you're probably right.  At least this will force me to learn how to create and restore a backup.
