### ISSUE TITLE
Updating and getting some odd errors........

### ISSUE THREAD

**Issue by Freejack01** [Akkadius/akk-stack#21]
doing the make bash and then running update on a currently working install and getting this:

/home/eqemu/code/zone/../common/eqemu_logsys.h:421:69: note: in definition of macro 'OutF'
  421 |     ls.Out(debug_level, log_category, file, func, line, fmt::format(formatStr, ##__VA_ARGS__).c_str()); \
      |                                                                     ^~~~~~~~~
/home/eqemu/code/zone/cheat_manager.cpp:208:4: note: in expansion of macro 'LogCheat'
  208 |    LogCheat(fmt::runtime(message));
      |    ^~~~~~~~
make[2]: *** [zone/CMakeFiles/zone.dir/build.make:251: zone/CMakeFiles/zone.dir/cheat_manager.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:993: zone/CMakeFiles/zone.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

it get's about 64% before it completely errors out, I see a few errors earlier basically saying the same thing about the runtime is not a member of fmt. 

Has something changed?

**Comment by Akkadius** [comment]
This is from cpp20 upgrade. Containers need to be updated and then cmake needs to be re-ran and submodules updated.

```
rm CMakeCache.txt
git submodules update
```

Then re-run your build
