### ISSUE TITLE
Bots

### ISSUE THREAD

**Issue by pittbull** [Akkadius/akk-stack#7]
Hi.

Trying to enable bots via the perl script, but it ends up by stating my binaries are not compiled for bots.

Have looked around for options, but cannot find any. :)

**Comment by shoolz** [comment]
bash/ssh into your eqemu server container.  
navigate to the /home/eqemu/assets/scripts folder and edit the makefile.  

change line 207 and add -DEQEMU_ENABLE_BOTS=ON to the cmake command. the entire line should read:

 cd ~/code && git submodule init && git submodule update && mkdir -p build && cd build && cmake -DEQEMU_BUILD_LOGIN=ON -DEQEMU_ENABLE_BOTS=ON -DEQEMU_BUILD_LUA=ON -G 'Unix Makefiles' ..   

save
navigate back to /home/eqemu
run: make init-build
and then make build

it will recompile the binaries with the bots option. I had the same issue as you and this worked for me. good luck!
