### ISSUE TITLE
Newb had a failure

### ISSUE THREAD

**Issue by IMay1280** [Akkadius/akk-stack#8]
Followed your install guide as best as I could, but I am new to Linux in general so it was a bit like herding cats for me...  Clean Ubuntu VM install, got Docker/Docker Compose installed without issue, followed steps up to the instruction to use a simple "make install".  Ran into a permissions issue so I used "sudo make install" instead.

Pulls went fine, Steps 1-6 completed successfully, then the train derailed and I'm not sure why.

![Errors](https://user-images.githubusercontent.com/93810595/140597329-bd61bdbd-eb89-4ab7-ae5c-e139a080c78b.jpg)

**Comment by 5000thinmints** [comment]
I've found everything regarding this docker goes best in root.

If still struggling with bind issues, or others reading this in the future try;

netstat -pna | grep 3306

3306 is the port having issues in this case (replace 3306 with 9000 if that's giving you issue, idea is the same), then it should list anything using a 3306 port that you can just go and sudo kill the id of.  Then you can try make again. However, if you just see docker containers using the port you can try a few things in increasing severity;
1. Reboot, sometimes this works not sure why
2. While in the docker folder docker-compose down, then trying again
3. docker rm -f $(docker ps -aq) down while in the docker folder, then trying again
4. Totally delete your eqemu server docker folder (rm -rf) and the other generic docker folder in /opt/ composnerd or something, you'll have to reboot then download everything again, but at least maybe then it might work. Maybe.

**Comment by khinch** [comment]
I'm seeing this also. I have a bare-metal install of Ubuntu 20.04.3. I have tried using the Snap package that comes with the Ubuntu installer, and also installed via following the official docs (https://docs.docker.com/engine/install/ubuntu/ and https://docs.docker.com/compose/install/). 

The steps suggested by 5000thinmints did not work for me, the error is always the same. 

![image](https://user-images.githubusercontent.com/13088378/154965102-8171350b-ab04-4159-a23a-e5b54856ac4b.png)

**Comment by tiphae** [comment]
I'm trying this on Unraid, and am running into the same problem - it fails after running 'make install' when trying to bind the port  3306.

![unraid1](https://user-images.githubusercontent.com/17076102/160264067-19f1128c-2f63-477d-aec5-0a46fe47530e.png)

When I check the Unraid docker GUI after this process fails, I see this:
![unraid2](https://user-images.githubusercontent.com/17076102/160264092-31f835b6-ca13-415c-925e-7ea35641f2ac.png)

I wasn't expecting multiple docker entries, so maybe I'm doing something wrong (though I'm following the instructions). Are all of those trying to bind to 3306?

**Comment by Akkadius** [comment]
This is not an error specific to `akk-stack`

You need to 

* Have the address on the local machine to be able to bind to (IP Address). If you don't it will give you the error
* Have the port available to be bound to on the machine. If you have MySQL installed on the host listening on `3306` you are not going to be able to bind to `3306`

**Comment by tiphae** [comment]
Thanks for replying, apologies as this is my first manual docker install (rather than using the unraid community apps or docker hub). 

I picked a docker network ip that wasn't in use (172.17.0.98 - the nearest docker ip otherwise is .19). 

I do have a mariadb docker running, but it's docker network ip is .8, and the port is mapped to server port 4406 (docker 3306->server 4406). Checking the docker allocations nothing else is set to use 3306 on the server side. Running the grep command above works without error, but returns no users of 3306. I also tried stopping the mariadb container to free up the docker port incase it was the problem, but it still fails.

**Comment by xackery** [comment]
To update these challenges I wrote in other issues, but:
run:
sudo chmod 666 /var/run/docker.sock
to give your current user access to the docker space
set the ip address to 0.0.0.0 during the environment setting tweak
run:
make install

it should run fine. When it's done, go into your eqemu_config.json and edit the world->localaddress and world->address to be your  WAN ip address. Leave the tcp->ip line to 0.0.0.0

This shoul remedy all the above situations.
